DELETE FROM votes;
ALTER TABLE votes ALTER COLUMN ID RESTART WITH 1;
DELETE FROM sessions;
ALTER TABLE sessions ALTER COLUMN ID RESTART WITH 1;
DELETE FROM associates;
ALTER TABLE associates ALTER COLUMN ID RESTART WITH 1;
DELETE FROM agendas;
ALTER TABLE agendas ALTER COLUMN ID RESTART WITH 1;
